on:
  push:
  pull_request:

jobs:
  scc_job:
    runs-on: ubuntu-latest
    name: SLOC counter and COCOMO report
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get the lines of code.
        id: scc
        uses: iryanbell/scc-docker-action@v1.0.2
        with:
          args: ${{ env.workspace }}
